config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'application#index'
  resources :imports do
    member do
      post :start
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
# frozen_string_literal: true

class Customer < ApplicationRecord
  belongs_to :import

  validates :first_name, :last_name, presence: true, length: { minimum: 2 }
  validates :email, presence: true,
                    format: { with: URI::MailTo::EMAIL_REGEXP },
                    uniqueness: true
  validates :date_of_birth,
            presence: true,
            inclusion: {
              in: (100.years.ago)..(18.years.ago),
              message: 'must be bigger than 18 and smaller than 100 years'
            }
end

app/models/import.rb
# frozen_string_literal: true

class Import < ApplicationRecord
  has_one_attached :file

  enum status: {
    created: 'created',
    pending: 'pending',
    started: 'started',
    completed: 'completed'
  }

  validates :title, presence: true
  validates :file, attached: true,
                   content_type: { in: 'text/csv', message: 'is not a CSV' }

  scope :created, -> { where(status: :created) }
  scope :started, lambda {
    where(status: %i[pending started]).order(started_at: :desc)
  }
  scope :completed, lambda {
    where(status: :completed).order(completed_at: :desc)
  }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  def index; end

  rescue_from ActiveRecord::RecordNotFound do
    head :not_found
  end
end

app/controllers/imports_controller.rb
# frozen_string_literal: true

class ImportsController < ApplicationController
  before_action :find_import, only: %i[show start edit update destroy]

  def index
    @created_imports = Import.created.decorate
    @started_imports = Import.started.decorate
    @completed_imports = Import.completed.decorate
  end

  def show
    @import = ImportDecorator.decorate_one(@import)
  end

  def create
    result = Imports::Create.new(create_params).call
    @import = result[:object]
    if result[:success]
      redirect_to import_url(@import)
    else
      @errors = result[:errors]
      render :new
    end
  end

  def new
    @import = Import.new
  end

  def start
    result = Imports::Start.new(@import).call

    # do not handle error case for now
    redirect_to import_url(@import) if result[:success]
  end

  def edit; end

  def update
    result = Imports::Update.new(@import, update_params).call

    if result[:success]
      redirect_to import_url(@import)
    else
      @errors = result[:errors]
      render :edit
    end
  end

  def destroy
    result = Imports::Destroy.new(@import).call

    # do not handle error case for now
    redirect_to imports_url if result[:success]
  end

  private

  def create_params
    params.require(:import).permit(:title, :file)
  end

  def update_params
    params.require(:import).permit(:title)
  end

  def find_import
    @import = Import.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/application/index.html.haml
%h4
  Title page

app/views/imports/_actions.html.haml
- if import.created?
  = link_to "Start", start_import_path(import), method: :post, class: 'btn btn-primary'
= link_to "Edit", edit_import_path(import), class: 'btn btn-success'
- unless import.started?
  = link_to "Delete", import_path(import), class: 'btn btn-danger', data: { confirm: 'Are you sure?' }, method: :delete

app/views/imports/_completed_imports.html.haml
%h4
  Completed imports
%table.table#completed-imports
  %thead
    %tr
      %th Title
      %th Processed
      %th Errors
      %th Duration
      %th Completed
      %th
  %tbody
    - @completed_imports.each do |import|
      %tr
        %td= link_to import.title, import_path(import)
        %td= import.processed
        %td= import.errors_count
        %td= import.duration
        %td= import.completed_at
        %td{align: 'right'}= render partial: 'actions', locals: {import: import}

app/views/imports/_created_imports.html.haml
%h4
  Created imports
%table.table#created-imports
  %thead
    %tr
      %th Title
      %th
  %tbody
    - @created_imports.each do |import|
      %tr
        %td= link_to import.title, import_path(import)
        %td{'align' => 'right'}
          = render partial: 'actions', locals: { import: import }

app/views/imports/_finished_imports.html.haml
%h4
  Finished imports
%table.table
  %thead
    %tr
      %th Title
      %th Processed
      %th Errors
      %th Started
      %th Completed
      %th Actions
  %tbody
    - @finished_imports.each do |import|
      %tr
        %td
          = import.title
        %td
          = import.processed
        %td
          = import.errors_count
        %td
          = import.started_at
        %td
          = import.completed_at
        %td
          Delete

app/views/imports/_started_imports.html.haml
%h4
  Started imports
%table.table
  %thead
    %tr
      %th Title
      %th Total
      %th Progress
      %th Errors
      %th Started
      %th
  %tbody
    - @started_imports.each do |import|
      %tr
        %td= link_to import.title, import_path(import)
        %td= import.total_count
        %td= import.progress
        %td= import.errors
        %td= import.started_at
        %td{align: 'right'}= render partial: 'actions', locals: {import: import}

app/views/imports/edit.html.haml
= form_for @import, html: { class: 'col-md-4 offset-md-4' } do |form|
  %h4.mx-auto
    Edit Import
  - if @errors
    %div.errors
      Errors:
      = @errors.join(";")
  .form-group
    = form.label :title, "Title"
    = form.text_field :title, class: 'form-control'
  = form.submit "Update", class: "btn btn-primary full-width"

app/views/imports/index.html.haml
.col-sm-8.offset-sm-2
  = render partial: 'created_imports'
  %br
  = render partial: 'started_imports'
  %br
  = render partial: 'completed_imports'

app/views/imports/new.html.haml
= form_for @import, html: { class: 'col-md-4 offset-md-4' } do |form|
  %h4.mx-auto
    New Import
  - if @errors
    %div.errors
      Errors:
      = @errors.join(";")
  .form-group
    = form.label :title, "Title"
    = form.text_field :title, class: 'form-control'
  .form-group
    = form.file_field :file, accept: 'text/csv'
  = form.submit "Create", class: "btn btn-primary full-width"

app/views/imports/show.html.haml
%h4
  Import details

%div.col-sm-6.offset-sm-3
  %table.table
    %thead
      %th
        Attribute
      %th
        Details

    %tbody
      - @import.details.each do |detail|
        %tr
          %td=detail[:title]
          %td=detail[:value]
  .actions
    = render partial: 'actions', locals: { import: @import }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title CsvImporter
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render partial: 'shared/navbar'
    = yield

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  = link_to "Matic", root_path, class: 'navbar-brand'
  %ul.navbar-nav.my-2.my-lg-0.ml-auto
    %li.nav-item.active.right
      = link_to "Imports", imports_path, class: 'nav-link'
    %li.nav-item.active.right
      = link_to "New Import", new_import_path, class: 'nav-link', id: 'new_import'